import { GoogleGenerativeAI } from '@google/generative-ai';

const getApiKey = (): string => {
  // Settings page key takes precedence, then .env variable
  const stored = localStorage.getItem('studyai_api_key');
  if (stored && stored.trim()) return stored.trim();
  const envKey = import.meta.env.VITE_GEMINI_API_KEY as string;
  if (envKey && envKey !== 'your_gemini_api_key_here') return envKey;
  throw new Error(
    'Gemini API key not set. Go to Settings and enter your API key, ' +
    'or set VITE_GEMINI_API_KEY in the .env file.'
  );
};

const genAI = () => new GoogleGenerativeAI(getApiKey());

const MODEL_CANDIDATES = [
  (import.meta.env.VITE_GEMINI_MODEL as string) || 'gemini-2.0-flash',
  'gemini-2.0-flash',
  'gemini-1.5-flash-latest',
  'gemini-1.5-flash',
];

const getUniqueModels = (): string[] => {
  return Array.from(new Set(MODEL_CANDIDATES.filter(Boolean)));
};

const isModelNotSupportedError = (error: unknown): boolean => {
  const message = error instanceof Error ? error.message : String(error);
  return (
    /404/i.test(message) ||
    /not found/i.test(message) ||
    /not supported/i.test(message)
  );
};

const normalizeGeminiError = (error: unknown): Error => {
  const message = error instanceof Error ? error.message : String(error);
  const lower = message.toLowerCase();

  if (lower.includes('429') || lower.includes('quota exceeded')) {
    return new Error(
      'Gemini quota exceeded (HTTP 429). Your API project currently has no available quota. ' +
        'Use a valid Gemini API key from Google AI Studio, enable billing if required, ' +
        'or wait for quota reset and try again.'
    );
  }

  if (lower.includes('401') || lower.includes('403') || lower.includes('api key not valid')) {
    return new Error(
      'Gemini authentication failed. Please verify your API key in Settings or .env.'
    );
  }

  return new Error(`Gemini request failed: ${message}`);
};

const isQuotaExceededError = (error: unknown): boolean => {
  const message = normalizeGeminiError(error).message.toLowerCase();
  return message.includes('quota exceeded') || message.includes('http 429');
};

const buildQuotaFallbackNotice = (): string => {
  return (
    '> Note: Gemini quota is currently unavailable, so this answer is generated by StudyAI fallback mode.\n\n'
  );
};

const buildFallbackChatResponse = (message: string): string => {
  const topic = message.trim() || 'this topic';
  return (
    buildQuotaFallbackNotice() +
    `## Quick Help: ${topic}\n\n` +
    `### What It Is\n` +
    `- ${topic} is a concept worth learning step by step.\n\n` +
    `### Study Plan\n` +
    `1. Start with the core definition.\n` +
    `2. Learn 3 key ideas and one example for each.\n` +
    `3. Solve a short practice question.\n` +
    `4. Summarize it in your own words.\n\n` +
    `### Try This Next\n` +
    `- Ask: \"Explain ${topic} for a beginner with examples.\"\n` +
    `- Ask: \"Give me a 5-question quiz on ${topic}.\"\n`
  );
};

const buildFallbackExplanation = (topic: string): string => {
  return (
    buildQuotaFallbackNotice() +
    `# ${topic}\n\n` +
    `## Definition\n` +
    `- ${topic} is a subject you can understand by breaking it into smaller parts.\n\n` +
    `## Key Concepts\n` +
    `- **Foundations**: Learn core terms and basic rules first.\n` +
    `- **Mechanism**: Understand how the parts connect.\n` +
    `- **Application**: Practice with real examples and problems.\n\n` +
    `## Example\n` +
    `- Pick one real-life scenario where ${topic} appears.\n` +
    `- Explain what happens step by step.\n\n` +
    `## Why It Matters\n` +
    `- It helps build deeper understanding and problem-solving skills.\n\n` +
    `## Summary\n` +
    `- Master the basics, apply with examples, and review with short quizzes.\n`
  );
};

const buildFallbackNotes = (topic: string): string => {
  return (
    buildQuotaFallbackNotice() +
    `# Study Notes: ${topic}\n\n` +
    `## Key Definitions\n` +
    `- **${topic}**: A topic studied through concepts, examples, and practice.\n\n` +
    `## Core Concepts\n` +
    `- Understand basic terminology first.\n` +
    `- Connect each concept to an example.\n` +
    `- Practice recall using short self-tests.\n\n` +
    `## Important Details\n` +
    `- Break long ideas into smaller points.\n` +
    `- Compare similar concepts to avoid confusion.\n` +
    `- Review mistakes and correct them immediately.\n\n` +
    `## Summary\n` +
    `- Learn, apply, test, and revise in short cycles.\n`
  );
};

const buildFallbackQuiz = (topic: string, count: number): QuizQuestion[] => {
  const safeCount = Math.max(1, Math.min(10, count));
  return Array.from({ length: safeCount }, (_, i) => ({
    question: `(${i + 1}) Which study strategy is best when learning ${topic}?`,
    options: [
      'Memorize without understanding',
      'Learn concepts, then practice with examples',
      'Skip revision completely',
      'Only read answers, never attempt questions',
    ],
    correctIndex: 1,
    explanation:
      `For ${topic}, concept understanding plus practice is the most effective approach.`,
  }));
};

async function withModelFallback<T>(
  fn: (modelName: string) => Promise<T>
): Promise<T> {
  const tried: string[] = [];
  let lastError: unknown = null;

  for (const modelName of getUniqueModels()) {
    tried.push(modelName);
    try {
      return await fn(modelName);
    } catch (error) {
      lastError = error;
      if (!isModelNotSupportedError(error)) {
        throw normalizeGeminiError(error);
      }
    }
  }

  const detail = normalizeGeminiError(lastError).message;
  throw new Error(
    `No supported Gemini model was available. Tried: ${tried.join(', ')}. ${detail}`
  );
}

export interface ChatMessage {
  role: 'user' | 'model';
  parts: string;
}

export async function sendChatMessage(
  history: ChatMessage[],
  message: string
): Promise<string> {
  const systemPrefix =
    'You are StudyAI, an expert AI study tutor. You help students understand topics clearly. ' +
    'Always explain concepts in a simple, structured way. Use bullet points, numbered lists, ' +
    'headings, and examples when helpful. ';

  try {
    return await withModelFallback(async (modelName) => {
      const model = genAI().getGenerativeModel({ model: modelName });
      const chat = model.startChat({
        history: history.map((m) => ({
          role: m.role,
          parts: [{ text: m.parts }],
        })),
        generationConfig: { maxOutputTokens: 2048 },
      });

      const result = await chat.sendMessage(systemPrefix + message);
      return result.response.text();
    });
  } catch (error) {
    if (isQuotaExceededError(error)) {
      return buildFallbackChatResponse(message);
    }
    throw error;
  }
}

export async function generateExplanation(topic: string): Promise<string> {
  const prompt = `You are an expert tutor. Generate a comprehensive explanation for the topic: "${topic}".
Include:
- A clear definition
- Key concepts and ideas
- How it works (with examples)
- Why it matters
- A short summary

Format with headings, bullet points, and examples. Be thorough but student-friendly.`;
  try {
    return await withModelFallback(async (modelName) => {
      const model = genAI().getGenerativeModel({ model: modelName });
      const result = await model.generateContent(prompt);
      return result.response.text();
    });
  } catch (error) {
    if (isQuotaExceededError(error)) {
      return buildFallbackExplanation(topic);
    }
    throw error;
  }
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export async function generateQuiz(
  topic: string,
  count: number = 5
): Promise<QuizQuestion[]> {
  const prompt = `Generate exactly ${count} multiple choice quiz questions about: "${topic}".

Return ONLY valid JSON array (no markdown, no explanation outside JSON), like:
[
  {
    "question": "Question text here?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctIndex": 0,
    "explanation": "Explanation why the answer is correct."
  }
]

Make sure questions are educational, clear, and appropriately challenging for students.`;

  let text = '';
  try {
    text = await withModelFallback(async (modelName) => {
      const model = genAI().getGenerativeModel({ model: modelName });
      const result = await model.generateContent(prompt);
      return result.response.text().trim();
    });
  } catch (error) {
    if (isQuotaExceededError(error)) {
      return buildFallbackQuiz(topic, count);
    }
    throw error;
  }

  // Strip potential markdown code fences
  const cleaned = text.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, '').trim();

  try {
    const parsed = JSON.parse(cleaned) as QuizQuestion[];
    return parsed;
  } catch {
    throw new Error('Failed to parse quiz response from AI.');
  }
}

export async function generateNotes(topic: string): Promise<string> {
  const prompt = `Create comprehensive study notes for the topic: "${topic}".

Format with:
# Main Title

## Key Definitions
- **Term**: Definition

## Core Concepts
- Bullet point explanations

## Important Details
- Details and sub-points

## Summary
A concise summary paragraph.

Make notes thorough, well-organized, and student-friendly.`;
  try {
    return await withModelFallback(async (modelName) => {
      const model = genAI().getGenerativeModel({ model: modelName });
      const result = await model.generateContent(prompt);
      return result.response.text();
    });
  } catch (error) {
    if (isQuotaExceededError(error)) {
      return buildFallbackNotes(topic);
    }
    throw error;
  }
}
